### ISSUE TITLE
Add option to randomize checkpoint on death

### ISSUE THREAD

**Issue by TheBetaM** [Zedb0T/OpenGoal-CheckpointRandomizer#74]
2 versions if possible:
-Randomized: Teleport to any random checkpoint after dying
-Strategic: Teleport to a fixed checkpoint seeded from the level where you died

**Comment by dallmeyer** [comment]
Think we might as well add the options for eco as well, some weirdos might have fun with it

**Comment by Zedb0T** [comment]
@TheBetaM added
