### ISSUE TITLE
Multiplayer Jak issues thread

### ISSUE THREAD

**Issue by Zedb0T** [Zedb0T/OpenGoal-CheckpointRandomizer#75]

**Comment by Zedb0T** [comment]
Ideas: -> before spawning a new player, change the cords of the current continue point to player 1s location + a determined offset, spawn player two, then change the continue points coordinates back to whatever they are supposed to be.

**Comment by Zedb0T** [comment]
Multiple controllers added by @dallmeyer is done.

Next just some basic tweaks

- If there is more than one target, freeze the camera mode as stick
- Automatically teleport any jak to the main jak if they get too far away
- If a side jak dies, respawn them automatically?
- Maybe make all jaks share a health pool??
- Enable ledge grabs and swimming for non primary jak
- Maybe let all jaks interact with NPCs/boat etc
- insert color change functions into the side jaks spawn method so we can tell them apart `(set! (-> *target2* draw color-mult x) (set! (-> *target2* draw color-mult y) 0.1))`

This is looking like its going to be great, just a few months of tweaks on the side and we should have something really good.

**Comment by dallmeyer** [comment]
most of these are fixed, and this repo is mostly an archive at this point so going to close this. 

current list of multiplayer issues: https://github.com/OpenGOAL-Unofficial-Mods/opengoal-multiplayer-rando-mod-pack/issues
